config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :agents
  devise_for :users
  resources :inquiries

  root 'home#index'

end

app/models/agent.rb
class Agent < ActiveRecord::Base
end

app/models/inquiry.rb
class Inquiry < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  before_action :set_agent, only: [:show, :edit, :update, :destroy]

  # GET /agents
  # GET /agents.json
  def index
    if params[:inquiry_id].present?
        @inquiry = Inquiry.find(params[:inquiry_id])
    end
    if @inquiry.present?
        @agents = Agent.where("location = ? AND (agent_type = ? OR agent_type = ?)", @inquiry.location, @inquiry.inquiry_type, 'both')
     else

       @agents = Agent.all
    end
  end

  # GET /agents/1
  # GET /agents/1.json
  def show
  end

  # GET /agents/new
  def new
    @agent = Agent.new
  end

  # GET /agents/1/edit
  def edit
  end

  # POST /agents
  # POST /agents.json
  def create
    @agent = Agent.new(agent_params)

    respond_to do |format|
      if @agent.save
        format.html { redirect_to @agent, notice: 'Agent was successfully created.' }
        format.json { render :show, status: :created, location: @agent }
      else
        format.html { render :new }
        format.json { render json: @agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agents/1
  # PATCH/PUT /agents/1.json
  def update
    respond_to do |format|
      if @agent.update(agent_params)
        format.html { redirect_to @agent, notice: 'Agent was successfully updated.' }
        format.json { render :show, status: :ok, location: @agent }
      else
        format.html { render :edit }
        format.json { render json: @agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agents/1
  # DELETE /agents/1.json
  def destroy
    @agent.destroy
    respond_to do |format|
      format.html { redirect_to agents_url, notice: 'Agent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agent
      @agent = Agent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agent_params
      params.require(:agent).permit!
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  before_action :set_inquiry, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /inquiries
  # GET /inquiries.json
  def index
    @inquiries = Inquiry.all
  end

  # GET /inquiries/1
  # GET /inquiries/1.json
  def show
  end

  # GET /inquiries/new
  def new
    @inquiry = Inquiry.new
  end

  # GET /inquiries/1/edit
  def edit
  end

  # POST /inquiries
  # POST /inquiries.json
  def create
    @inquiry = Inquiry.new(inquiry_params)

    respond_to do |format|
      if @inquiry.save
        format.html {redirect_to agents_path(inquiry_id: @inquiry.id)}
      else
        format.html { render :new }
        format.json { render json: @inquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inquiries/1
  # PATCH/PUT /inquiries/1.json
  def update
    respond_to do |format|
      if @inquiry.update(inquiry_params)
        format.html { redirect_to @inquiry, notice: 'Inquiry was successfully updated.' }
        format.json { render :show, status: :ok, location: @inquiry }
      else
        format.html { render :edit }
        format.json { render json: @inquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inquiries/1
  # DELETE /inquiries/1.json
  def destroy
    @inquiry.destroy
    respond_to do |format|
      format.html { redirect_to inquiries_url, notice: 'Inquiry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inquiry
      @inquiry = Inquiry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inquiry_params
      params.require(:inquiry).permit(:name, :email, :inquiry_type, :user_type, :proprietor_trade_license, :partner_registered_agreement, :limited_maa, :limited_certification_incorporation, :membership_of_chember, :vat_reg, :tin_number, :exim_license, :company_bank_account, :other_license, :commercial_invoice, :packing_list, :pro_forma_invoice, :shipping_documents, :proof_of_payment, :certificate_of_origin, :ex_erc_number, :insurance, :bond_license, :restricted_clearance, :import_reg_certificate, :export_reg_certificate, :location)
    end
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/views/agents/_form.html.erb
<%= form_for(@agent) do |f| %>
  <% if @agent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@agent.errors.count, "error") %> prohibited this agent from being saved:</h2>

      <ul>
      <% @agent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label 'name:' %><br>
    <%= f.text_field :name, class: 'form-control'%>
  </div>
  <div class="form-group">
    <%= f.label 'address:' %><br>
    <%= f.text_area :address, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= label_tag :location %><br>
    <%= f.select :location, options_for_select(['Dhaka', 'Chittagong', 'Benapol', 'Others']), {}, {:class=>"form-control" } %>
  </div>
  <div class="form-group">
    <%= f.label :agent_type %><br>
    <%= f.select :agent_type, options_for_select(["export", "import", "both"]), {}, {:class=>"form-control" } %>
  </div>
  <div class="form-group">
    <%= f.label 'phone:' %><br>
    <%= f.text_field :phone, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label 'mobile:' %><br>
    <%= f.text_field :mobile, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label 'fax:' %><br>
    <%= f.text_field :fax, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label 'email:' %><br>
    <%= f.text_field :email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label 'license:' %><br>
    <%= f.text_field :license, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label 'grading:' %><br>
    <%= f.text_field :grading, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit 'Agents entry', class: 'btn btn-info btn-lg' %>
  </div>
<% end %>

app/views/agents/edit.html.erb
<h1>Editing Agent</h1>

<%= render 'form' %>

<%= link_to 'Show', @agent %> |
<%= link_to 'Back', agents_path %>

app/views/agents/index.html.erb
<p id="notice"><%= notice %></p>

<h1 style="padding: 20px; color: #00838F;">Listing Agents</h1>

<table border="2" >
  <thead>
  
    <tr>
      <th  style="text-align: center; padding: 20px 20px;">Name</th>
      <th style="text-align: center; padding: 20px 20px;">Address</th>
      <th style="text-align: center; padding: 20px 20px;">Phone</th>
      <th style="text-align: center; padding: 20px 20px;">Mobile</th>
      <th style="text-align: center; padding: 20px 20px;">Fax</th>
      <th style="text-align: center; padding: 20px 20px;">Email</th>
      <th style="text-align: center; padding: 20px 20px;">License</th>
      <th style="text-align: center; padding: 20px 20px;">Grading</th>
          </tr>
    
  </thead>

  <tbody>
    <% @agents.each do |agent| %>
      <tr>
        <td style="text-align: center; padding: 20px 20px;"><%= agent.name %></td>
        <td style="text-align: center; padding: 20px 20px;"><%= agent.address %></td>
        <td style="text-align: center; padding: 20px 20px;"><%= agent.phone %></td>
        <td style="text-align: center; padding: 20px 20px;"><%= agent.mobile %></td>
        <td style="text-align: center; padding: 20px 20px;"><%= agent.fax %></td>
        <td style="text-align: center; padding: 20px 20px;"><%= agent.email %></td>
        <td style="text-align: center; padding: 20px 20px;"><%= agent.license %></td>
        <td style="text-align: center; padding: 20px 20px;"><%= agent.grading %></td>
        <td style="text-align: center; padding: 20px 20px; font-weight: bold;"><%= link_to 'Show', agent %></td>
        <td style="text-align: center; padding: 20px 20px; font-weight: bold;"><%= link_to 'Edit', edit_agent_path(agent) %></td>
        <td style="text-align: center; padding: 20px 10px; font-weight: bold;"><%= link_to 'Destroy', agent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Agent', new_agent_path %>

app/views/agents/new.html.erb
<h1>New Agent</h1>

<%= render 'form' %>

<%= link_to 'Back', agents_path %>

app/views/agents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @agent.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @agent.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @agent.phone %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @agent.mobile %>
</p>

<p>
  <strong>Fax:</strong>
  <%= @agent.fax %>
</p>

<p>
  <strong>Email:</strong>
  <%= @agent.email %>
</p>

<p>
  <strong>License:</strong>
  <%= @agent.license %>
</p>

<p>
  <strong>Grading:</strong>
  <%= @agent.grading %>
</p>

<%= link_to 'Edit', edit_agent_path(@agent) %> |
<%= link_to 'Back', agents_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/inquiries/_form.html.erb
<%= form_for(@inquiry) do |f| %>
  <% if @inquiry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inquiry.errors.count, "error") %> prohibited this inquiry from being saved:</h2>

      <ul>
      <% @inquiry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= label_tag :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= label_tag :email %><br>
    <%= f.text_field :email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= label_tag :location %><br>
    <%= f.select :location, options_for_select(['Dhaka', 'Chittagong', 'Benapol', 'Others']), {}, {:class=>"form-control" } %>
  </div>
  <div class="form-group">
    <%= label_tag :inquiry_type %><br />
    <%= label_tag :inquiry_type, "Export", :value => "export"  %>
    <%= f.radio_button :inquiry_type, 'export' %>
    <%= label_tag :inquiry_type, "Import", :value => "import" %>
    <%= f.radio_button :inquiry_type, 'import', :checked => true %>
    <%= label_tag :inquiry_type, "Both", :value => "both" %>
    <%= f.radio_button :inquiry_type, 'both' %>
  </div>
  <div class="form-group">
    <%= label_tag :user_type %><br>
    <%= f.select :user_type, options_for_select(['Proprietor', 'Partner', 'Limited Company', 'Others']), {}, {:class=>"form-control" } %>
  </div>
  <div class="form-group">
    <%= label_tag :proprietor_trade_license %><br>
    <%= label_tag :proprietor_trade_license, "Yes"  %>
    <%= f.radio_button :proprietor_trade_license, true %>
    <%= label_tag :proprietor_trade_license, "No" %>
    <%= f.radio_button :proprietor_trade_license, false, :checked => true %>
  </div>
  <div class="form-group">
    <%= label_tag :partner_registered_agreement %><br>
      <%= label_tag :partner_registered_agreement, "Yes"  %>
    <%= f.radio_button :partner_registered_agreement, true %>
    <%= label_tag :partner_registered_agreement, "No" %>
    <%= f.radio_button :partner_registered_agreement, false, :checked => true %>
  </div>
  <div class="form-group">
    <%= label_tag 'If you are from a Limited Company, do you have the Memorandum & Articles Association?' %><br>
      <%= label_tag :limited_maa, "Yes"  %>
    <%= f.radio_button :limited_maa, true %>
    <%= label_tag :limited_maa, "No" %>
    <%= f.radio_button :limited_maa, false, :checked => true %>
  </div>
  <div class="form-group">
    <%= label_tag 'If you are from a Limited Company, do you have the Certification of Incorporation?' %><br>
   <%= label_tag :limited_certification_incorporation, "Yes"  %>
    <%= f.radio_button :limited_certification_incorporation, true %>
    <%= label_tag :limited_certification_incorporation, "No" %>
    <%= f.radio_button :limited_certification_incorporation, false, :checked => true %>
  </div>
   <%= label_tag '**If you are not a Proprietor or a Partner or not from any Limited Company then contact with us. Call us 00000000000.' %>
  <div class="form-group">
   <%= label_tag 'Do you have these following required documents for export/import' %><br><br>
    <%= f.check_box :membership_of_chember %>
    <%= label_tag 'Membership Certificate from recognized Chamber/Trade Association' %>
  </div>
  <div class="form-group">
    <%= f.check_box :vat_reg %>
    <%= label_tag 'VAT Registration' %>
  </div>
  <div class="form-group">
    <%= f.check_box :tin_number %>
    <%= label_tag 'TIN Registration' %>
  </div>
  <div class="form-group">
    <%= f.check_box :exim_license %>
    <%= label_tag 'Export or Import License' %>
  </div>
  <div class="form-group">
    <%= f.check_box :company_bank_account %>
    <%= label_tag 'Bank Account in the name of the company and Bank certificate confirming account with bank' %>
  </div>
  <div class="form-group">
    <%= f.check_box :other_license %>
    <%= label_tag 'Any other licenses or permits depending on type of business' %>
  </div>
  <div class="form-group">
  <%= label_tag 'Do you have these following Required Documents for Shipment?' %><br><br>
    <%= f.check_box :commercial_invoice %>
    <%= label_tag 'Commercial Invoice (original)' %>
  </div>
  <div class="form-group">
        <%= f.check_box :packing_list %>
        <%= label_tag 'Packing List (original)' %>
  </div>
  <div class="form-group">
    <%= f.check_box :pro_forma_invoice %>
    <%= label_tag 'Pro-forma Invoice (original)' %>
  </div>
  <div class="form-group">
    <%= f.check_box :shipping_documents %>
    <%= label_tag 'Shipping Documents (BL/AWB/LR)' %>
  </div>
  <div class="form-group">
    <%= f.check_box :proof_of_payment %>
    <%= label_tag 'Proof of Payment (TT/LC/Contract/PO against which EXP issued by CCI&E)' %>
  </div>
  <div class="form-group">
    <%= f.check_box :certificate_of_origin %>
    <%= label_tag 'Certificate of Origin (if required by buyer, will be mentioned in LC)' %>
  </div>
  <div class="form-group">
    <%= f.check_box :ex_erc_number %>
    <%= label_tag 'Exporters ERC No. copy' %>
  </div>
  <div class="form-group">
    <%= f.check_box :insurance %>
    <%= label_tag 'Insurance (if required)' %>
  </div>
  <div class="form-group">
    <%= f.check_box :bond_license %>
    <%= label_tag ' Bond License (if bonded) copy' %>
  </div>
  <div class="form-group">
    <%= f.check_box :restricted_clearance %>
    <%= label_tag 'In case of special or restricted goods, necessary clearance papers from relevant authority' %>
  </div>
    <div class="form-group">
    <label>Do you have Import Registration Certificate (IRC)?</label><br>
    <%= f.radio_button :import_reg_certificate, true %>
    <%= label_tag :import_reg_certificate, "Yes"  %>
    <%= f.radio_button :import_reg_certificate, false, :checked => true %>
    <%= label_tag :import_reg_certificate, "No" %>
  </div>
    <div class="form-group">
    <%= label_tag 'Do you have Export Registration Certificate (ERC)?' %><br>
    <%= f.radio_button :export_reg_certificate, true %>
    <%= label_tag :export_reg_certificate, "Yes"  %>
    <%= f.radio_button :export_reg_certificate, false, :checked => true %>
    <%= label_tag :export_reg_certificate, "No" %>
    
  </div>
  <div class="form-group">
    <%= f.submit 'Submit', class: 'btn btn-info btn-lg' %>
  </div>
<% end %>

app/views/inquiries/edit.html.erb
<h1>Editing Inquiry</h1>

<%= render 'form' %>

<%= link_to 'Show', @inquiry %> |
<%= link_to 'Back', inquiries_path %>

app/views/inquiries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Inquiries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Inquiry type</th>
      <th>User type</th>
      <th>Proprietor trade license</th>
      <th>Partner registered agreement</th>
      <th>Limited maa</th>
      <th>Limited certification incorporation</th>
      <th>Membership of chember</th>
      <th>Vat reg</th>
      <th>Tin number</th>
      <th>Exim license</th>
      <th>Company bank account</th>
      <th>Other license</th>
      <th>Commercial invoice</th>
      <th>Packing list</th>
      <th>Pro forma invoice</th>
      <th>Shipping documents</th>
      <th>Proof of payment</th>
      <th>Certificate of origin</th>
      <th>Ex erc number</th>
      <th>Insurance</th>
      <th>Bond license</th>
      <th>Restricted clearance</th>
      <th>Import reg certificate</th>
      <th>Export reg certificate</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inquiries.each do |inquiry| %>
      <tr>
        <td><%= inquiry.name %></td>
        <td><%= inquiry.email %></td>
        <td><%= inquiry.inquiry_type %></td>
        <td><%= inquiry.user_type %></td>
        <td><%= inquiry.proprietor_trade_license %></td>
        <td><%= inquiry.partner_registered_agreement %></td>
        <td><%= inquiry.limited_maa %></td>
        <td><%= inquiry.limited_certification_incorporation %></td>
        <td><%= inquiry.membership_of_chember %></td>
        <td><%= inquiry.vat_reg %></td>
        <td><%= inquiry.tin_number %></td>
        <td><%= inquiry.exim_license %></td>
        <td><%= inquiry.company_bank_account %></td>
        <td><%= inquiry.other_license %></td>
        <td><%= inquiry.commercial_invoice %></td>
        <td><%= inquiry.packing_list %></td>
        <td><%= inquiry.pro_forma_invoice %></td>
        <td><%= inquiry.shipping_documents %></td>
        <td><%= inquiry.proof_of_payment %></td>
        <td><%= inquiry.certificate_of_origin %></td>
        <td><%= inquiry.ex_erc_number %></td>
        <td><%= inquiry.insurance %></td>
        <td><%= inquiry.bond_license %></td>
        <td><%= inquiry.restricted_clearance %></td>
        <td><%= inquiry.import_reg_certificate %></td>
        <td><%= inquiry.export_reg_certificate %></td>
        <td><%= inquiry.location %></td>
        <td><%= link_to 'Show', inquiry %></td>
        <td><%= link_to 'Edit', edit_inquiry_path(inquiry) %></td>
        <td><%= link_to 'Destroy', inquiry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inquiry', new_inquiry_path %>

app/views/inquiries/new.html.erb
<h3><b>Required information</b></h3>
<div class="title-border"></div>
<%= render 'form' %>

<%= link_to 'Back', inquiries_path %>

app/views/inquiries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @inquiry.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @inquiry.email %>
</p>

<p>
  <strong>Inquiry type:</strong>
  <%= @inquiry.inquiry_type %>
</p>

<p>
  <strong>User type:</strong>
  <%= @inquiry.user_type %>
</p>

<p>
  <strong>Proprietor trade license:</strong>
  <%= @inquiry.proprietor_trade_license %>
</p>

<p>
  <strong>Partner registered agreement:</strong>
  <%= @inquiry.partner_registered_agreement %>
</p>

<p>
  <strong>Limited maa:</strong>
  <%= @inquiry.limited_maa %>
</p>

<p>
  <strong>Limited certification incorporation:</strong>
  <%= @inquiry.limited_certification_incorporation %>
</p>

<p>
  <strong>Membership of chember:</strong>
  <%= @inquiry.membership_of_chember %>
</p>

<p>
  <strong>Vat reg:</strong>
  <%= @inquiry.vat_reg %>
</p>

<p>
  <strong>Tin number:</strong>
  <%= @inquiry.tin_number %>
</p>

<p>
  <strong>Exim license:</strong>
  <%= @inquiry.exim_license %>
</p>

<p>
  <strong>Company bank account:</strong>
  <%= @inquiry.company_bank_account %>
</p>

<p>
  <strong>Other license:</strong>
  <%= @inquiry.other_license %>
</p>

<p>
  <strong>Commercial invoice:</strong>
  <%= @inquiry.commercial_invoice %>
</p>

<p>
  <strong>Packing list:</strong>
  <%= @inquiry.packing_list %>
</p>

<p>
  <strong>Pro forma invoice:</strong>
  <%= @inquiry.pro_forma_invoice %>
</p>

<p>
  <strong>Shipping documents:</strong>
  <%= @inquiry.shipping_documents %>
</p>

<p>
  <strong>Proof of payment:</strong>
  <%= @inquiry.proof_of_payment %>
</p>

<p>
  <strong>Certificate of origin:</strong>
  <%= @inquiry.certificate_of_origin %>
</p>

<p>
  <strong>Ex erc number:</strong>
  <%= @inquiry.ex_erc_number %>
</p>

<p>
  <strong>Insurance:</strong>
  <%= @inquiry.insurance %>
</p>

<p>
  <strong>Bond license:</strong>
  <%= @inquiry.bond_license %>
</p>

<p>
  <strong>Restricted clearance:</strong>
  <%= @inquiry.restricted_clearance %>
</p>

<p>
  <strong>Import reg certificate:</strong>
  <%= @inquiry.import_reg_certificate %>
</p>

<p>
  <strong>Export reg certificate:</strong>
  <%= @inquiry.export_reg_certificate %>
</p>

<p>
  <strong>Location:</strong>
  <%= @inquiry.location %>
</p>

<%= link_to 'Edit', edit_inquiry_path(@inquiry) %> |
<%= link_to 'Back', inquiries_path %>

app/views/layouts/_background.html.erb
<div class="background">
		<div class="slide">
			<img class="img-responsive" src="/images/bg.jpg">
			<!-- <div class="text">
				<h2>Import Export Business</h2>
			</div> -->
		</div>
	</div>

app/views/layouts/_header.html.erb
<div class="header">
	<div class="inner-body">
		<div class="col-sm-12">
			<div class="col-sm-3">
				<h1><b>Tradeshi</b></h1>
			</div>
			<div class="col-sm-9">
				<nav>
					<ul>
						<a href="#"><i class="fa fa-user fa-lg" aria-hidden="true"></i></a>

						<% if current_user.present? %>
						<a href="<%= destroy_user_session_path %>" data-method="delete"><li class="test-class" id="home active"><b>Sign Out</b></li></a>
						<% else %> 
						<a href="<%= user_session_path %>"><li class="test-class" id="home active"><b>Sign In</b></li></a>
						<% end %>
						<a href="cnf.html"><li class="test-class" id="cnf"><b>cnf agents</b></li></a>
						<a href="/inquiries/new"><li class="test-class" id="req"><b>requirements</b></li></a>
						
						<a href="/home/index"><li class="test-class" id="home active"><b>home</b></li></a>
						<div class="extra"></div>
					</ul>
				</nav>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CnfAgentSearch</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
  <%= csrf_meta_tags %>
</head>
<body>
<!-- <p class="notice"><%#= notice %></p>
<p class="alert"><%#= alert %></p> -->
<%= render 'layouts/header' %>
<%= render 'layouts/background' %>
<div class="clearfix"></div>
<div class="container">
	<div class="row">
		<div class="col-sm-12">
			<%= yield %>
		</div>						
	</div>
</div>
<div id="footer">
		<h5><b>Powered by Tradeshi Team @ 2017</b></h5>
	</div>
</body>
</html>